In [1]:
import numpy as np

**Array Dimensions**

In [2]:
Array_D_0 = np.array(35)
print(Array_D_0)

35


In [3]:
print(f"matrix Array_D_0 is {Array_D_0.ndim} dimention")

matrix Array_D_0 is 0 dimention


In [4]:
print(f"Array_D_0 Shape is : {Array_D_0.shape}")

Array_D_0 Shape is : ()


In [5]:
Array_D_1 = np.array([1, 2, 3, 4])
print(Array_D_1)

[1 2 3 4]


In [6]:

print(f"matrix Array_D_1 is {Array_D_1.ndim} dimention")

matrix Array_D_1 is 1 dimention


In [7]:
print(f"Array_D_1 Shape is : {Array_D_1.shape}")

Array_D_1 Shape is : (4,)


In [8]:
Array_D_2 = np.array([[1, 2, 3],
                      [4, 5, 6]])
print(Array_D_2)

[[1 2 3]
 [4 5 6]]


In [9]:
print(f"matrix Array_D_2 is {Array_D_2.ndim} dimention")

matrix Array_D_2 is 2 dimention


In [10]:
print(f"Array_D_2 Shape is : {Array_D_2.shape}")

Array_D_2 Shape is : (2, 3)


In [11]:
Array_D_3 = np.array([[[1, 2, 3], [4, 5, 6]],
                      [[7, 8, 9], [10, 11, 12]]])
print(Array_D_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(f"matrix Array_D_3 is {Array_D_3.ndim} dimention")

matrix Array_D_3 is 3 dimention


In [13]:
print(f"Array_D_3 Shape is : {Array_D_3.shape}")

Array_D_3 Shape is : (2, 2, 3)


**sum(), max(), min() and mean()**

In [14]:
Array_1 = np.array([[2, 8, 11, 3, 15],
                    [6, 1, 9, 25, 19],
                    [14, 5, 7, 4, 8]])

print(Array_1)

[[ 2  8 11  3 15]
 [ 6  1  9 25 19]
 [14  5  7  4  8]]


In [15]:
print(f"matrix Array_1 is {Array_1.ndim} dimention")

matrix Array_1 is 2 dimention


In [16]:
print(f"Array_1 Shape is : {Array_1.shape}")

Array_1 Shape is : (3, 5)


In [17]:
print(f"sum is : {Array_1.sum()}")

sum is : 137


In [18]:
print(f"sum of each column is : {Array_1.sum(axis=0)}")

sum of each column is : [22 14 27 32 42]


In [19]:
print(f"sum of each row is : {Array_1.sum(axis=1)}")

sum of each row is : [39 60 38]


In [20]:
print(f"max is : {Array_1.max()}")

max is : 25


In [21]:
print(f"max of each column is : {Array_1.max(axis=0)}")

max of each column is : [14  8 11 25 19]


In [22]:
print(f"max of each row is : {Array_1.max(axis=1)}")

max of each row is : [15 25 14]


In [23]:
print(f"min is : {Array_1.min()}")

min is : 1


In [24]:
print(f"min of each column is : {Array_1.min(axis=0)}")

min of each column is : [2 1 7 3 8]


In [25]:
print(f"min of each row is : {Array_1.min(axis=0)}")

min of each row is : [2 1 7 3 8]


In [26]:
print(f"mean is : {Array_1.mean()}")

mean is : 9.133333333333333


In [27]:
print(f"mean of each column is : {Array_1.mean(axis=0)}")

mean of each column is : [ 7.33333333  4.66666667  9.         10.66666667 14.        ]


In [28]:
print(f"mean of each row is : {Array_1.mean(axis=1)}")

mean of each row is : [ 7.8 12.   7.6]


In [29]:
print(Array_1[1:3, 2:5])

[[ 9 25 19]
 [ 7  4  8]]


In [30]:
Array_1.ravel()

array([ 2,  8, 11,  3, 15,  6,  1,  9, 25, 19, 14,  5,  7,  4,  8])

ravel() ===> array flattened

In [31]:
Array_1

array([[ 2,  8, 11,  3, 15],
       [ 6,  1,  9, 25, 19],
       [14,  5,  7,  4,  8]])

In [32]:
Array_1.T

array([[ 2,  6, 14],
       [ 8,  1,  5],
       [11,  9,  7],
       [ 3, 25,  4],
       [15, 19,  8]])

T ===> transposed

In [33]:
Array_1.shape

(3, 5)

In [34]:
Array_1.T.shape

(5, 3)

**Reshaping**

In [35]:
Array_1.reshape(3, -1)

array([[ 2,  8, 11,  3, 15],
       [ 6,  1,  9, 25, 19],
       [14,  5,  7,  4,  8]])

In [36]:
Array_1.view()

array([[ 2,  8, 11,  3, 15],
       [ 6,  1,  9, 25, 19],
       [14,  5,  7,  4,  8]])

In [37]:
Array_1[1, 0] = 255
Array_1

array([[  2,   8,  11,   3,  15],
       [255,   1,   9,  25,  19],
       [ 14,   5,   7,   4,   8]])

**np.array()**

In [38]:
Array_2 = np.array([1.63, 8.96, 7.53, 4.25], dtype= 'i')
print(Array_2)

[1 8 7 4]


In [39]:
Array_3 = np.array([86.14, 53.7, 11.32, 43.26])
print(Array_3)

[86.14 53.7  11.32 43.26]


**Type of Array**

In [40]:
print(Array_3.astype("i")) # or print(Array_3.astype(int))

[86 53 11 43]


In [41]:
print(Array_3.astype("S")) # or print(Array_3.astype(str))

[b'86.14' b'53.7' b'11.32' b'43.26']


In [42]:
print(Array_3.astype("F"))

[86.14+0.j 53.7 +0.j 11.32+0.j 43.26+0.j]


In [43]:
print(Array_3.astype(bool))

[ True  True  True  True]


In [44]:
Array_4 = np.array([4, 8, 3, 7, 11, 3, 5, 5, 1, 8, 9, 6, 3, 1, 5, 8])

print(np.where(Array_4 == 5))

(array([ 6,  7, 14]),)


In [45]:
print(np.where(Array_4 == 4))

(array([0]),)


In [46]:
print(np.where(Array_4 == 3))

(array([ 2,  5, 12]),)


In [47]:
print(np.where(Array_4 == 1))

(array([ 8, 13]),)


In [48]:
print(np.where(Array_4 == 11))

(array([4]),)


In [49]:
print(np.where(Array_4 % 2 == 0))

(array([ 0,  1,  9, 11, 15]),)


In [50]:
print(np.where(Array_4 % 2 == 1))

(array([ 2,  3,  4,  5,  6,  7,  8, 10, 12, 13, 14]),)


In [51]:
print(np.where(Array_4 % 2 != 0))

(array([ 2,  3,  4,  5,  6,  7,  8, 10, 12, 13, 14]),)


**Random Array**

In [52]:
from numpy import random

In [53]:
rand_1 = random.randint(100)
rand_1

99

In [54]:
rand_2 = random.randint(100, size=5)
rand_2

array([54, 95, 43, 57, 25])

In [55]:
rand_3 = random.randint(100, size=(3, 5))
rand_3

array([[26,  0, 57, 28,  1],
       [11, 78, 11,  0, 63],
       [56, 27, 92, 46, 55]])

In [56]:
rand_4 = random.rand()
rand_4

0.6905610267693493

In [57]:
rand_5 = random.rand(4)
rand_5

array([0.40840044, 0.50345024, 0.75244854, 0.57012253])

In [58]:
rand_6 = random.rand(4, 3)
rand_6

array([[0.39057368, 0.61827729, 0.72274771],
       [0.62170281, 0.99460736, 0.6912655 ],
       [0.10917305, 0.73612334, 0.33656444],
       [0.90237095, 0.75425707, 0.12930777]])

**np.arange()**

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(1, 50, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [61]:
np.arange(0, 25, step=3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [62]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [63]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [65]:
np.arange(6).reshape(1, 4)

ValueError: ignored

**np.linspace()**

In [66]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
np.linspace(1, 20, num=7)

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [68]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

**Zero Array**

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**One Array**

In [71]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [72]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [73]:
np.ones((3, 6), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

**Empty Array**

In [74]:
np.empty(4)

array([0.40840044, 0.50345024, 0.75244854, 0.57012253])

In [75]:
np.empty((2, 3))

array([[0.0e+000, 4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323, 2.5e-323]])

**Full Array**

In [76]:
np.full(3, 4)

array([4, 4, 4])

In [77]:
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**Diagonal matrix**

In [78]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
rand_7 = np.arange(5)
rand_7

array([0, 1, 2, 3, 4])

**Radical**

In [80]:
np.sqrt(rand_7)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

**Exponential**

In [81]:
np.exp(rand_7)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**np.ndarray()**

In [82]:
Array_5 = np.ndarray([1, 2, 3])
Array_5

array([[[0.0e+000, 4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323, 2.5e-323]]])

In [83]:
Array_5.shape

(1, 2, 3)

In [84]:
Array_6 = np.arange(15).reshape(3, 5)
Array_6

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
print(Array_6.ndim)

2


In [86]:
type(Array_6)

numpy.ndarray

In [87]:
Array_6.dtype

dtype('int64')

In [88]:
Array_6.dtype.name

'int64'

In [89]:
Array_6.size

15

In [90]:
Array_6.itemsize

8

In [91]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [92]:
Array_7 = np.array([4, 7, 3])
Array_7

array([4, 7, 3])

In [93]:
Array_8 = np.array([4, 7, 3], dtype=complex)
Array_8

array([4.+0.j, 7.+0.j, 3.+0.j])

**Elementary Arithmetic**

In [94]:
Array_9 = np.array([20, 30, 40, 50, 60, 70])
Array_10 = np.arange(6)

In [95]:
Array_9

array([20, 30, 40, 50, 60, 70])

In [96]:
Array_10

array([0, 1, 2, 3, 4, 5])

In [97]:
Array_9 - Array_10

array([20, 29, 38, 47, 56, 65])

In [98]:
Array_10 ** 2

array([ 0,  1,  4,  9, 16, 25])

In [99]:
15 * np.sin(Array_9)

array([ 13.69417876, -14.82047436,  11.17669741,  -3.93562281,
        -4.57215932,  11.60836022])

In [100]:
Array_9 < 50

array([ True,  True,  True, False, False, False])

In [101]:
Array_11 = np.array([[1, 1],
                     [0, 1]])

Array_12 = np.array([[2, 0],
                     [3, 4]])

In [102]:
Array_11 + Array_12

array([[3, 1],
       [3, 5]])

In [103]:
Array_11 * Array_12

array([[2, 0],
       [0, 4]])

In [104]:
Array_11 @ Array_12

array([[5, 4],
       [3, 4]])

In [105]:
Array_11.dot(Array_12)

array([[5, 4],
       [3, 4]])