In [1]:
import numpy as np

In [2]:
A_1 = np.array([1, 2, 3, 4])
A_1

array([1, 2, 3, 4])

In [3]:
type(A_1)

numpy.ndarray

*shape : to check the shape of the array*

In [4]:
A_1.shape

(4,)

*ndim : to check the dimension (rank) of the array*

In [5]:
A_1.ndim

1

*size : to check the no. of elements in the array*

In [6]:
A_1.size

4

In [7]:
A_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
A_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
type(A_2)

numpy.ndarray

In [9]:
A_2.shape

(2, 4)

In [10]:
A_2.ndim

2

In [11]:
A_2.size

8

In [12]:
A_3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
A_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
type(A_3)

numpy.ndarray

In [14]:
A_3.shape

(1, 3, 3)

In [15]:
A_3.ndim

3

In [16]:
A_3.size

9