### Zeros Array - An array in which all values are 0.

### ZA = np.zeros(shape, dtype)

- We can define the shape and data-type of zeros array.
- We can create 1-D, 2-D, as well 3-D zeros array.
- The default data-type is float..

* ndim - to check the dimension of the array
* shape - to check the shape of the array
* size - to check the size of the array

In [1]:
import numpy as np

In [2]:
z_1 = np.zeros(3)
z_1

array([0., 0., 0.])

In [3]:
z_1 = np.zeros(3, dtype= int)
z_1

array([0, 0, 0])

In [4]:
z_1 = np.zeros(15, dtype= int)
z_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
type(z_1)

numpy.ndarray

In [6]:
z_1.ndim

1

In [7]:
z_2 = np.zeros((3, 4))
z_2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
z_2 = np.zeros((3, 4), dtype= int)
z_2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
z_2.shape

(3, 4)

In [10]:
z_2.size

12

In [11]:
z_3 = np.zeros((2, 3, 4))
z_3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
z_3.ndim

3

In [13]:
z_3.size

24