### Ones Array - An array in which all values are 1.

### O = np.ones(shape, dtype)

- We can define the shape and data-type of ones array.
- We can create 1-D, 2-D, as well 3-D ones array.
- The default data-type is float.



* ndim - to check the dimension of the array
* shape - to check the shape of the array
* size - to check the size of the array



In [1]:
import numpy as np

**1 D**

In [2]:
o_1 = np.ones(3)
o_1

array([1., 1., 1.])

In [3]:
o_1 = np.ones(3, dtype= int)
o_1

array([1, 1, 1])

In [4]:
type(o_1)

numpy.ndarray

In [5]:
o_1.shape

(3,)

In [6]:
o_1.ndim

1

In [7]:
o_1.size

3

**2 D**

In [8]:
o_2 = np.ones((2, 3))
o_2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
o_2 = np.ones((2, 3), dtype= int)
o_2

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
type(o_2)

numpy.ndarray

In [11]:
o_2.shape

(2, 3)

In [12]:
o_2.ndim

2

In [13]:
o_2.size

6

**3 D**

In [14]:
o_3 = np.ones((2, 3, 4))
o_3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
o_3 = np.ones((2, 3, 4), dtype= int)
o_3

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [16]:
type(o_3)

numpy.ndarray

In [17]:
# o_3.shape
np.shape(o_3)

(2, 3, 4)

In [18]:
# o_3.ndim
np.ndim(o_3)

3

In [19]:
# o_3.size
np.size(o_3)

24