In [1]:
import numpy as np

In [2]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [3]:
np.ones((2, 2, 2), dtype= str)

array([[['1', '1'],
        ['1', '1']],

       [['1', '1'],
        ['1', '1']]], dtype='<U1')

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones(5, dtype= float)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones(5, dtype= int)

array([1, 1, 1, 1, 1])

In [7]:
np.ones(5, int)

array([1, 1, 1, 1, 1])