### Full Array - An array in which all values are same (constant)

### F = np.full(shape, fill_value)

- We can define the shape, and pass the value to be filled in the 'Full Arrays'.
- We can create 1-D, 2-D, as well as 3-D Full Array, with integer, float or string values.
- The default data-type is Integer.



* ndim - to check the dimension of the array
* shape - to check the shape of the array
* size - to check the size of the array

In [1]:
import numpy as np

**1 D**

In [2]:
f_1 = np.full(3)
f_1

TypeError: full() missing 1 required positional argument: 'fill_value'

In [3]:
f_1 = np.full(3, 45)
f_1

array([45, 45, 45])

In [4]:
f_1 = np.full(4, 79, dtype= float)
f_1

array([79., 79., 79., 79.])

In [5]:
f_1 = np.full(5, 61.23)
f_1

array([61.23, 61.23, 61.23, 61.23, 61.23])

In [6]:
type(f_1)

numpy.ndarray

In [7]:
f_1.shape

(5,)

In [8]:
f_1.ndim

1

**2 D**

In [9]:
f_2 = np.full((2, 4), 91)
f_2

array([[91, 91, 91, 91],
       [91, 91, 91, 91]])

In [10]:
f_2 = np.full((2, 4), 26.47, dtype= int)
f_2

array([[26, 26, 26, 26],
       [26, 26, 26, 26]])

In [11]:
f_2.shape

(2, 4)

In [12]:
f_2.ndim

2

In [13]:
np.full((2, 3), 46.11, dtype= str)

array([['4', '4', '4'],
       ['4', '4', '4']], dtype='<U1')

In [14]:
np.full((2, 4), 9539846.11, dtype= str)

array([['9', '9', '9', '9'],
       ['9', '9', '9', '9']], dtype='<U1')

In [15]:
np.full((2, 4), "9539846.11", dtype= str)

array([['9', '9', '9', '9'],
       ['9', '9', '9', '9']], dtype='<U1')

In [16]:
np.full((2, 4), "9539846.11")

array([['9539846.11', '9539846.11', '9539846.11', '9539846.11'],
       ['9539846.11', '9539846.11', '9539846.11', '9539846.11']],
      dtype='<U10')

**3 D**

In [17]:
f_3 = np.full((2, 3, 4), "Python")
f_3

array([[['Python', 'Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python', 'Python']],

       [['Python', 'Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python', 'Python']]], dtype='<U6')

In [18]:
f_3.shape

(2, 3, 4)

In [19]:
f_3.ndim

3

In [20]:
f_3.size

24