### The Random Module contain the functions which are used for generating random numbers.

In [1]:
import numpy as np
from numpy import random

#### 1. Random Function

It returns random float number(s) between 0 and 1.

In [2]:
np.random.random()

0.5284839701094396

In [3]:
np.random.random(5)

array([0.75164908, 0.47269127, 0.38896356, 0.58991037, 0.82407943])

In [4]:
np.random.random(2, 3)

TypeError: random() takes at most 1 positional argument (2 given)

In [5]:
np.random.random((2, 3))

array([[0.89993966, 0.51152594, 0.80319554],
       [0.18171762, 0.34944973, 0.86227267]])

In [6]:
np.random.random((3, 2, 5))

array([[[0.14571066, 0.65049934, 0.43266876, 0.29476395, 0.49529634],
        [0.68095317, 0.26347622, 0.67889226, 0.04290437, 0.76510086]],

       [[0.04589128, 0.64248892, 0.44475725, 0.32985577, 0.17768007],
        [0.5833216 , 0.86455275, 0.9078908 , 0.90582454, 0.13492574]],

       [[0.73067637, 0.42924628, 0.03787081, 0.19086001, 0.96091082],
        [0.26100056, 0.25991228, 0.83178798, 0.78361584, 0.50947134]]])

#### 2. Randint Function
- It generates random integer number(s) between given range. 
- By default, the range starts from 0.
- The numbers can repeat.

In [7]:
np.random.randint(2, 45)

35

In [8]:
np.random.randint(3, 30, 9)

array([ 7, 20, 21, 23, 11, 26,  7, 22,  8])

In [9]:
np.random.randint(5)

2

In [10]:
np.random.randint(5)

2

##### 3. Rand Function

It returns random float number(s) between 0 and 1.

In [11]:
np.random.rand()

0.07875316960273293

In [12]:
np.random.rand(5)

array([0.43315642, 0.07556248, 0.14245222, 0.58802423, 0.49266315])

In [13]:
np.random.rand(3, 4)

array([[0.70638917, 0.50600123, 0.57930652, 0.57459698],
       [0.45062043, 0.94065217, 0.28876512, 0.06146827],
       [0.48172395, 0.1165485 , 0.67757561, 0.81838711]])

In [14]:
np.random.rand(3, 4, 5)

array([[[0.50563172, 0.73822019, 0.00919723, 0.05396245, 0.47045158],
        [0.76122797, 0.67869079, 0.47922279, 0.8901119 , 0.4569685 ],
        [0.13770837, 0.69982198, 0.38408248, 0.72357063, 0.78700123],
        [0.43500435, 0.61871732, 0.3166691 , 0.50855653, 0.72245438]],

       [[0.53628729, 0.80751034, 0.80819294, 0.41065566, 0.11651258],
        [0.95369327, 0.74085103, 0.66426215, 0.65000642, 0.16700846],
        [0.53634467, 0.47929215, 0.628152  , 0.67064765, 0.49513272],
        [0.34177707, 0.57443692, 0.37099758, 0.18530285, 0.85259459]],

       [[0.22944161, 0.36964708, 0.18881326, 0.30392265, 0.13243249],
        [0.72467909, 0.64755264, 0.72751599, 0.39900684, 0.25771046],
        [0.61412636, 0.45852015, 0.54059652, 0.09670046, 0.89990758],
        [0.77871302, 0.70367659, 0.22060815, 0.6923378 , 0.60762403]]])

##### 4. Randn Function

It returns random float numbers (postive and negative both) in the form of array.

In [15]:
np.random.randn()

1.645918916517589

In [16]:
np.random.randn(6)

array([ 0.61679535,  0.84424033, -0.65205494, -0.16129225, -1.80430155,
       -0.16441292])

In [17]:
np.random.randn(3, 4, 4)

array([[[ 1.05409194,  0.49165335,  0.45620032,  0.79767023],
        [ 0.11948229,  1.12178884,  0.59118604,  0.99406383],
        [ 1.45633018,  0.08354195, -0.09115142, -0.98603018],
        [-2.50253341, -0.35238478, -0.34677547,  0.32033156]],

       [[-1.33090825,  0.54132919,  0.42145532, -0.9048122 ],
        [-0.54669384,  0.5699388 ,  1.39751983, -0.04943119],
        [ 0.41625472, -2.05554118,  0.23581767,  1.28895761],
        [ 1.19580457, -0.55598412,  0.64410063,  0.04450891]],

       [[-1.51696737, -0.57892788,  0.42477102,  0.10650876],
        [-0.16600045,  0.67100365, -0.62158031, -0.27985637],
        [-1.84576363, -0.79834589,  0.25735279,  0.13856929],
        [-1.75698091, -2.22492664, -0.9270626 ,  0.66375028]]])

#### 5. Uniform Function

- It returns random float number(s) between the given range of values.
- The random numbers can't repeat.
- By default, the range starts from 0.
- If nothing is passed in (), it will return a float number between 0 and 1.

In [18]:
np.random.uniform(8, 3)

5.742271735560595

In [19]:
np.random.uniform(3, 10, 12)

array([4.47242304, 9.63992567, 4.2959932 , 4.64730486, 6.12333365,
       4.44016719, 9.10966098, 7.82947357, 3.96729876, 8.45841557,
       9.82987682, 9.73791903])

In [20]:
np.random.uniform(5)

1.3267164332307049

In [21]:
np.random.uniform(5)

2.344537438980698

In [22]:
np.random.uniform()

0.33493956024056526

#### 6. Choice Function
- It returns random integer number(s) from the given sequence.
- The range starts from 0 by default.
- If only 1 element is passed, then it will return a number between 0 and that element.
- By default, replace = True , which means the numbers can repeat.

In [23]:
np.random.choice([6, 11, 8, 5, 46, 37, 13, 15, 7, 66, 1, 9, 51])

37

In [24]:
np.random.choice([6, 11, 8, 5, 46, 37, 13, 15, 7, 66, 1, 9, 51], 3)

array([ 7,  8, 11])

In [25]:
np.random.choice(15, 120)

array([ 8,  7, 11,  8,  5,  4, 10,  7,  6, 14,  4,  7, 11,  0, 10,  3,  0,
        5,  6, 14,  3,  9,  8,  5, 11,  4, 12,  5, 10, 10,  4,  5,  8,  3,
       11, 14, 13,  9,  1,  8,  0, 12, 14, 11,  3,  8, 11,  3,  5, 10,  8,
        6,  7,  1, 10,  8,  5, 14,  3, 11,  1, 11, 13,  3,  1,  2,  8,  4,
       12,  8,  2,  2,  1, 11,  4, 12,  8, 12,  0, 12,  8,  0,  8,  9, 14,
        1, 11,  2, 12,  2,  8,  9, 10,  1,  3,  1, 11, 14,  5, 14,  4, 14,
        8,  5,  1,  0,  5,  7,  0,  8, 10,  6,  2,  5, 13,  2,  3,  1,  2,
       10])

In [26]:
np.random.choice(19)

6

In [27]:
np.random.choice([6, 11, 8, 5, 46, 37, 13, 15, 7, 66, 1, 9, 51], size= 7)

array([ 7,  5, 46,  7,  1, 51, 15])

In [28]:
np.random.choice([6, 11, 8, 5, 46, 37, 13, 15, 7, 66, 1, 9, 51], size= 7, replace= False)

array([ 9, 46, 11,  8, 66,  6,  5])

In [29]:
np.random.choice([6, 11, 8, 5, 46, 37, 13, 15, 7, 66, 1, 9, 51], size= 25, replace= False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [30]:
np.random.choice([6, 11, 8, 5, 46, 37, 13, 15, 7, 66, 1, 9, 51], size= 25, replace= True)

array([ 1, 66,  6, 46,  5,  1,  9,  1, 46, 46,  7,  5, 13,  5, 66,  7, 13,
       15, 66, 51,  7, 13,  1, 15, 51])