### Linspace Function returns evenly (linearly) spaced values within a given interval.

###### np.linspace(start_value, stop_value , num=50, endpoint=False, retstep=True, dtype=None)

Note - By deafult it shows 50 values

In [1]:
import numpy as np

In [2]:
np.linspace(2, 20, num= 10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [3]:
np.linspace(2, 20, num= 10, endpoint= True)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [4]:
np.linspace(2, 20, num= 10, endpoint= False)

array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2])

In [5]:
np.linspace(2, 20, num= 10, endpoint= True, retstep= True)

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)

In [6]:
np.linspace(2, 20, num= 10, endpoint= False, retstep= True)

(array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2]), 1.8)

In [7]:
np.linspace(2, 20, num= 10, endpoint= True, retstep= False)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [8]:
np.linspace(2, 20, num= 10, endpoint= True, retstep= False, dtype= int)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.linspace(2, 20, num= 10, endpoint= True, retstep= True, dtype= int)

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]), 2.0)

In [10]:
np.linspace(2, 20, num= 10, endpoint= True, retstep= True, dtype= str)

(array(['2.0', '4.0', '6.0', '8.0', '10.0', '12.0', '14.0', '16.0', '18.0',
        '20.0'], dtype='<U32'),
 2.0)

In [11]:
np.linspace(2, 20, num= 10, endpoint= False, retstep= True, dtype= str)

(array(['2.0', '3.8', '5.6', '7.4', '9.2', '11.0', '12.8', '14.6', '16.4',
        '18.2'], dtype='<U32'),
 1.8)

In [12]:
A = np.linspace(3, 30)
A

array([ 3.        ,  3.55102041,  4.10204082,  4.65306122,  5.20408163,
        5.75510204,  6.30612245,  6.85714286,  7.40816327,  7.95918367,
        8.51020408,  9.06122449,  9.6122449 , 10.16326531, 10.71428571,
       11.26530612, 11.81632653, 12.36734694, 12.91836735, 13.46938776,
       14.02040816, 14.57142857, 15.12244898, 15.67346939, 16.2244898 ,
       16.7755102 , 17.32653061, 17.87755102, 18.42857143, 18.97959184,
       19.53061224, 20.08163265, 20.63265306, 21.18367347, 21.73469388,
       22.28571429, 22.83673469, 23.3877551 , 23.93877551, 24.48979592,
       25.04081633, 25.59183673, 26.14285714, 26.69387755, 27.24489796,
       27.79591837, 28.34693878, 28.89795918, 29.44897959, 30.        ])

In [13]:
len(A)

50

In [14]:
np.linspace(3, 30, num= 23, retstep= True)

(array([ 3.        ,  4.22727273,  5.45454545,  6.68181818,  7.90909091,
         9.13636364, 10.36363636, 11.59090909, 12.81818182, 14.04545455,
        15.27272727, 16.5       , 17.72727273, 18.95454545, 20.18181818,
        21.40909091, 22.63636364, 23.86363636, 25.09090909, 26.31818182,
        27.54545455, 28.77272727, 30.        ]),
 1.2272727272727273)