In [1]:
import numpy as np

In [2]:
np.linspace(5, 50, num= 7)

array([ 5. , 12.5, 20. , 27.5, 35. , 42.5, 50. ])

In [3]:
np.linspace(5, 50, num= 7, endpoint= True)

array([ 5. , 12.5, 20. , 27.5, 35. , 42.5, 50. ])

In [4]:
np.linspace(5, 50, num= 7, endpoint= False)

array([ 5.        , 11.42857143, 17.85714286, 24.28571429, 30.71428571,
       37.14285714, 43.57142857])

In [5]:
np.linspace(5, 50, num= 7, endpoint= True, retstep= True)

(array([ 5. , 12.5, 20. , 27.5, 35. , 42.5, 50. ]), 7.5)

In [6]:
np.linspace(5, 50, num= 7, endpoint= False, retstep= True)

(array([ 5.        , 11.42857143, 17.85714286, 24.28571429, 30.71428571,
        37.14285714, 43.57142857]),
 6.428571428571429)

In [7]:
np.linspace(5, 50, num= 7, endpoint= False, dtype= int)

array([ 5, 11, 17, 24, 30, 37, 43])

In [8]:
np.linspace(5, 50, num= 7, endpoint= True, dtype= int)

array([ 5, 12, 20, 27, 35, 42, 50])