##### Empty Function is used to create an array of arbitrary values, of given shape and datatype, without intializing the entries

###### Syntax :
    np.empty(shape, dtype)

- Shape can given in list or tuple from.
- The default datatype is float.

In [1]:
import numpy as np

In [2]:
np.empty()

TypeError: empty() missing required argument 'shape' (pos 0)

In [3]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.empty(6, dtype= int)

array([1612738420,  779120224, 1851880052, 1936683123, 1702045797,
       1613325932])

In [5]:
np.empty(5, dtype= object)

array([None, None, None, None, None], dtype=object)

In [6]:
np.empty((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.empty((5, 3), dtype= int)

array([[3801155, 5570652, 6619251],
       [7536754, 4718684, 5242975],
       [6029379, 7340097, 4456560],
       [7602273, 6029409, 7274572],
       [6357091, 6029420, 6619220]])

In [8]:
np.empty((4, 4), dtype= object)

array([[None, None, None, None],
       [None, None, None, None],
       [None, None, None, None],
       [None, None, None, None]], dtype=object)

In [9]:
np.empty([2, 3, 5])

array([[[1.35220322e-311, 1.01777523e-321, 0.00000000e+000,
         0.00000000e+000, 1.42413554e-306],
        [5.02034658e+175, 1.43602341e-051, 6.38269950e-067,
         4.19318689e+175, 2.17570700e-076],
        [1.32284373e-071, 1.04915136e-153, 6.32299154e+233,
         2.87505047e+161, 1.70098498e+256]],

       [[5.49109388e-143, 1.06396443e+224, 3.96041428e+246,
         1.16318408e-028, 4.46979726e-033],
        [9.95305904e-043, 1.53618564e-051, 3.92070426e+179,
         2.24151504e+174, 3.36163259e-067],
        [8.26108324e-072, 2.29569732e-028, 3.69908966e-057,
         5.74015544e+180, 1.94919988e-153]]])

In [10]:
np.empty((2, 3, 5))

array([[[1.35220322e-311, 1.01777523e-321, 0.00000000e+000,
         0.00000000e+000, 1.42413554e-306],
        [5.02034658e+175, 1.43602341e-051, 6.38269950e-067,
         4.19318689e+175, 2.17570700e-076],
        [1.32284373e-071, 1.04915136e-153, 6.32299154e+233,
         2.87505047e+161, 1.70098498e+256]],

       [[5.49109388e-143, 1.06396443e+224, 3.96041428e+246,
         1.16318408e-028, 4.46979726e-033],
        [9.95305904e-043, 1.53618564e-051, 3.92070426e+179,
         2.24151504e+174, 3.36163259e-067],
        [8.26108324e-072, 2.29569732e-028, 3.69908966e-057,
         5.74015544e+180, 1.94919988e-153]]])

In [11]:
np.empty((2, 3, 5), dtype= int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [12]:
np.empty((2, 3, 5), dtype= object)

array([[[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]]], dtype=object)