#### It returns an identity array i.e., a square array with 1 on the main diagonal and all other elements are 0.

###### Syntax :
    np.identity(shape, dtype)

- It takes a single integer value only as shape.
- The No. of Rows and No. of Columns will be equal to the given integer value.
- The default datatype is float

In [1]:
import numpy as np

In [2]:
A = np.identity(4)
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.identity(5, dtype= int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [4]:
A.ndim

2

In [5]:
A.size

16

In [6]:
A.shape

(4, 4)

In [7]:
A * 25

array([[25.,  0.,  0.,  0.],
       [ 0., 25.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0., 25.]])

In [8]:
A * 7.41268

array([[7.41268, 0.     , 0.     , 0.     ],
       [0.     , 7.41268, 0.     , 0.     ],
       [0.     , 0.     , 7.41268, 0.     ],
       [0.     , 0.     , 0.     , 7.41268]])

In [9]:
A + 7

array([[8., 7., 7., 7.],
       [7., 8., 7., 7.],
       [7., 7., 8., 7.],
       [7., 7., 7., 8.]])