In [1]:
import numpy as np
from numpy import random

#### Ones Like Array - It returns an array of Ones, with the same shape & type as of the given array.

#### Syntax :
    np.ones_like(array, dtype)

In [2]:
A = np.array([21, 16, 35, 97])
A

array([21, 16, 35, 97])

In [3]:
B = np.random.random((4, 5))
B

array([[0.15371475, 0.32262146, 0.55121378, 0.86331787, 0.58877129],
       [0.74299444, 0.81425184, 0.96747712, 0.48360444, 0.66900493],
       [0.9420932 , 0.33975431, 0.68807856, 0.01974301, 0.20492343],
       [0.11837723, 0.65001016, 0.99965317, 0.31357126, 0.77784118]])

In [4]:
C = np.random.randn(5, 2)
C

array([[-0.42346863,  0.27246404],
       [ 0.42631526, -0.56721753],
       [-1.512789  , -0.99475241],
       [-0.19769131, -0.190236  ],
       [-0.32975632, -0.08726034]])

In [5]:
D = np.random.randn(2, 3, 4)
D

array([[[ 0.43463676,  0.73431708,  0.999424  ,  1.14135401],
        [ 0.10749933, -0.46166899, -0.19070032, -0.52148052],
        [-0.75262574, -0.1611996 ,  0.37563986,  1.1022082 ]],

       [[ 0.62315122, -1.43175499,  1.7090328 ,  0.68211378],
        [-0.55032015,  0.11646189, -0.97194624, -2.0884795 ],
        [-1.65631323, -1.93449254,  1.58457732,  0.18632336]]])

In [6]:
np.ones_like(A)

array([1, 1, 1, 1])

In [7]:
np.ones_like(B)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.ones_like(B, dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### Zeros Like Array - It returns an array of Zeros, with the same shape & type as of the given array.

#### Syntax :
    np.zeros_like(array, dtype)

In [9]:
np.zeros_like(A)

array([0, 0, 0, 0])

In [10]:
C

array([[-0.42346863,  0.27246404],
       [ 0.42631526, -0.56721753],
       [-1.512789  , -0.99475241],
       [-0.19769131, -0.190236  ],
       [-0.32975632, -0.08726034]])

In [11]:
np.zeros_like(C)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.zeros_like(C, dtype= int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

#### Full Like Array - It returns a full array of Constant element, with the same shape & type as of the given array.

#### Syntax :
    np.full_like(array, fill_value, dtype)

In [13]:
A

array([21, 16, 35, 97])

In [14]:
np.full_like(A, 7)

array([7, 7, 7, 7])

In [15]:
D

array([[[ 0.43463676,  0.73431708,  0.999424  ,  1.14135401],
        [ 0.10749933, -0.46166899, -0.19070032, -0.52148052],
        [-0.75262574, -0.1611996 ,  0.37563986,  1.1022082 ]],

       [[ 0.62315122, -1.43175499,  1.7090328 ,  0.68211378],
        [-0.55032015,  0.11646189, -0.97194624, -2.0884795 ],
        [-1.65631323, -1.93449254,  1.58457732,  0.18632336]]])

In [16]:
np.full_like(D, 75)

array([[[75., 75., 75., 75.],
        [75., 75., 75., 75.],
        [75., 75., 75., 75.]],

       [[75., 75., 75., 75.],
        [75., 75., 75., 75.],
        [75., 75., 75., 75.]]])

In [17]:
np.full_like(D, -75, int)

array([[[-75, -75, -75, -75],
        [-75, -75, -75, -75],
        [-75, -75, -75, -75]],

       [[-75, -75, -75, -75],
        [-75, -75, -75, -75],
        [-75, -75, -75, -75]]])