#### Diagonal Function - It is used to extract the diagonal elements of an array, or , used to construct a new diagonal array

#### Syntax :
    np.diag(a, k)

#### Note :
- If 'a' is a 2-D array, it extracts the diagonal elements. 
- If 'a' is a 1-D array, it constructs a 2-D array with elements of 'a' on diagonal.
- By default, k is 0. Use k>0 for diagonals above the main diagonal. Use k<0 for diagonals below the main diagonal.

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
A.ndim

2

In [4]:
np.diag(A)

array([1, 5, 9])

In [5]:
np.diag(A, k= 0)

array([1, 5, 9])

In [6]:
np.diag(A, k= 1)

array([2, 6])

In [7]:
np.diag(A, k= 2)

array([3])

In [8]:
np.diag(A, k= -1)

array([4, 8])

In [9]:
np.diag(A, k= -2)

array([7])

In [10]:
B = np.array([11, 22, 33, 44, 55])
B

array([11, 22, 33, 44, 55])

In [11]:
B.ndim

1

In [12]:
np.diag(B)

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0, 55]])

In [13]:
np.diag(B, k= 0)

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0, 55]])

In [14]:
np.diag(B, k= 1)

array([[ 0, 11,  0,  0,  0,  0],
       [ 0,  0, 22,  0,  0,  0],
       [ 0,  0,  0, 33,  0,  0],
       [ 0,  0,  0,  0, 44,  0],
       [ 0,  0,  0,  0,  0, 55],
       [ 0,  0,  0,  0,  0,  0]])

In [15]:
np.diag(B, k= 2)

array([[ 0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0, 22,  0,  0,  0],
       [ 0,  0,  0,  0, 33,  0,  0],
       [ 0,  0,  0,  0,  0, 44,  0],
       [ 0,  0,  0,  0,  0,  0, 55],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [16]:
np.diag(B, k= 3)

array([[ 0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 22,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 33,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 44,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 55],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [17]:
np.diag(B, k= 4)

array([[ 0,  0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 22,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 33,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 44,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 55],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [18]:
np.diag(B, k= -1)

array([[ 0,  0,  0,  0,  0,  0],
       [11,  0,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0,  0],
       [ 0,  0, 33,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0],
       [ 0,  0,  0,  0, 55,  0]])

In [19]:
np.diag(B, k= -2)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [11,  0,  0,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0,  0,  0],
       [ 0,  0, 33,  0,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0,  0],
       [ 0,  0,  0,  0, 55,  0,  0]])

In [20]:
np.diag(B, k= -5)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [11,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 33,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 55,  0,  0,  0,  0,  0]])

In [21]:
x = np.random.randn(2, 3, 4)
x

array([[[-1.17753035, -0.06305667, -0.8525808 , -1.00574451],
        [-1.54274235, -0.58834659,  0.23034739, -4.05230341],
        [ 0.71360226,  0.00446789, -0.1375678 ,  1.20356832]],

       [[ 1.98737268, -0.46166593,  0.21732031,  1.65428942],
        [ 0.09579511, -0.18113642,  0.7929917 , -1.43658724],
        [-0.41736787,  0.53418146,  0.89902188,  1.68432671]]])

In [22]:
np.diag(x)

ValueError: Input must be 1- or 2-d.