#### Transpose Function - It converts the Rows into Columns, and Columns into Rows

#### Syntax
    array.T
    or,
    np.transpose(array)

In [1]:
import numpy as np

#### Transpose of a 2-D array

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
A.shape

(2, 3)

In [6]:
A.T.shape

(3, 2)

#### Transpose of a 1-D array

In [7]:
B = np.array([11, 12, 13, 14, 15, 16, 17, 18])
B

array([11, 12, 13, 14, 15, 16, 17, 18])

In [8]:
B.T

array([11, 12, 13, 14, 15, 16, 17, 18])

In [9]:
B.shape

(8,)

In [10]:
B.T.shape

(8,)

#### Transpose of a 3-D array

In [11]:
C = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
C

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
C.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [13]:
C.shape

(1, 3, 3)

In [14]:
C.T.shape

(3, 3, 1)