### Unary Operators - Those operators that require only one operand.

These functions can be applied row-wise or column-wise by setting an 'axis' parameter

In [1]:
import numpy as np

In [2]:
A = np.array([5, 12, 48, 39, 51])
A

array([ 5, 12, 48, 39, 51])

In [3]:
print(A)

[ 5 12 48 39 51]


In [4]:
A.max()

51

In [5]:
np.max(A)

51

In [6]:
A.min()

5

In [7]:
np.min(A)

5

In [8]:
A.sum()

155

In [9]:
np.sum(A)

155

In [10]:
B = np.array([[1, 25, 47], [53, 90, 4]])
B

array([[ 1, 25, 47],
       [53, 90,  4]])

In [11]:
print(B)

[[ 1 25 47]
 [53 90  4]]


In [12]:
B.max()

90

In [13]:
B.max(axis= 0)

array([53, 90, 47])

In [14]:
B.max(axis= 1)

array([47, 90])

In [15]:
B.min()

1

In [16]:
B.min(axis= 0)

array([ 1, 25,  4])

In [17]:
B.min(axis= 1)

array([1, 4])

In [18]:
B.sum()

220

In [19]:
B.sum(axis= 0)

array([ 54, 115,  51])

In [20]:
B.sum(axis= 1)

array([ 73, 147])

In [21]:
C = np.arange(18)
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [22]:
D = np.arange(18).reshape(2, 3, 3)
D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [23]:
D.max()

17

In [24]:
D.max(axis= 0)

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [25]:
D.max(axis= 1)

array([[ 6,  7,  8],
       [15, 16, 17]])

In [26]:
D.min()

0

In [27]:
D.min(axis= 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
D.min(axis= 1)

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [29]:
D.sum()

153

In [30]:
D.sum(axis= 0)

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [31]:
D.sum(axis= 1)

array([[ 9, 12, 15],
       [36, 39, 42]])