Vstack or Hstack is used to combine two or more arrays to form a new array.

- Vstack - Combine the arrays vertically.
- Hstack - Combine the arrays horizontally.

In [1]:
import numpy as np

##### In 1-D Array

In [2]:
A = np.array([1, 2, 3, 4, 5])
print(A)

[1 2 3 4 5]


In [3]:
B = np.array(A * 2)
print(B)

[ 2  4  6  8 10]


In [4]:
C = np.array(A * 3)
print(C)

[ 3  6  9 12 15]


In [5]:
V_1 = np.vstack((A, B))
V_1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [6]:
V_1_1 = np.vstack((A, B, C))
V_1_1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [7]:
H_1 = np.hstack((A, B))
H_1

array([ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10])

In [8]:
H_1_1 = np.hstack((A, B, C))
H_1_1

array([ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  3,  6,  9, 12, 15])

In [9]:
A.shape

(5,)

In [10]:
B.shape

(5,)

In [11]:
C.shape

(5,)

In [12]:
V_1.shape

(2, 5)

In [13]:
V_1_1.shape

(3, 5)

In [14]:
H_1.shape

(10,)

In [15]:
H_1_1.shape

(15,)

##### In 2-D Array

In [16]:
P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(P)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
Q = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])
print(Q)

[[ 9 10 11 12]
 [13 14 15 16]]


In [18]:
V_2 = np.vstack((P, Q))
V_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
H_2 = np.hstack((P, Q))
H_2

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [20]:
P.shape

(2, 4)

In [21]:
Q.shape

(2, 4)

In [22]:
V_2.shape

(4, 4)

In [23]:
H_2.shape

(2, 8)

##### In 3-D Array

In [24]:
X = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
X

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
Y = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
Y

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [26]:
V_3 = np.vstack((X, Y))
V_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
H_3 = np.hstack((X, Y))
H_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [28]:
X.shape

(1, 3, 3)

In [29]:
Y.shape

(1, 3, 3)

In [30]:
V_3.shape

(2, 3, 3)

In [31]:
H_3.shape

(1, 6, 3)