Indexing is used to obtain particular element(s) or row(s) or column(s) from the numpy array(s)

Here, we pass the Index of the element to access it

The Index starts from 0, not from 1

It returns elements till "stop index - 1" index

In [1]:
import numpy as np

#### Indexing in 1-D Array

In [2]:
A = np.array([5, 36, 11, 23, 98, 43, 9, 85])
A

array([ 5, 36, 11, 23, 98, 43,  9, 85])

In [3]:
A[0]

5

In [4]:
A[3]

23

In [5]:
A[15]

IndexError: index 15 is out of bounds for axis 0 with size 8

In [6]:
A[:]

array([ 5, 36, 11, 23, 98, 43,  9, 85])

In [7]:
A[1:]

array([36, 11, 23, 98, 43,  9, 85])

In [8]:
A[2:]

array([11, 23, 98, 43,  9, 85])

In [9]:
A[: 1]

array([5])

In [10]:
A[: 6]

array([ 5, 36, 11, 23, 98, 43])

In [11]:
A[: 4]

array([ 5, 36, 11, 23])

In [12]:
A[2: 3]

array([11])

In [13]:
A[6: 8]

array([ 9, 85])

#### Indexing in 2-D Array

In [14]:
B = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [15]:
B[0]

array([11, 12, 13, 14])

In [16]:
B[1]

array([15, 16, 17, 18])

In [17]:
B[:]

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [18]:
B[0, 1: 2]

array([12])

In [19]:
B[0, 2: 4]

array([13, 14])

In [20]:
B[1, 2: 3]

array([17])

In [21]:
B[B > 14]

array([15, 16, 17, 18])

In [22]:
B[B < 16]

array([11, 12, 13, 14, 15])

#### Indexing in 3-D Array

In [23]:
C = np.array([[ [11, 12, 13], [14, 15, 16], [17, 18, 19]], [[20, 21, 22], [23, 24, 25], [26, 27, 28] ]])
C

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [24]:
C[0]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [25]:
C[1]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [26]:
C[:]

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [27]:
C[0, 1: 3, :]

array([[14, 15, 16],
       [17, 18, 19]])

In [28]:
C[1, : , 1: 3]

array([[21, 22],
       [24, 25],
       [27, 28]])

In [29]:
C[1, 1, 1]

24

In [30]:
C[1, 2, 1]

27