In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("preprocessed_dataset.csv")

In [3]:
df.head()

Unnamed: 0  PayloadMass  Flights  GridFins  Reused  Legs  Block  \
0           0  6104.959412        1         0       0     0    1.0   
1           1   525.000000        1         0       0     0    1.0   
2           2   677.000000        1         0       0     0    1.0   
3           3   500.000000        1         0       0     0    1.0   
4           4  3170.000000        1         0       0     0    1.0   

   ReusedCount  Class  Orbit_ES-L1  ...  Serial_B1048  Serial_B1049  \
0            0      0            0  ...             0             0   
1            0      0            0  ...             0             0   
2            0      0            0  ...             0             0   
3            0      0            0  ...             0             0   
4            0      0            0  ...             0             0   

   Serial_B1050  Serial_B1051  Serial_B1054  Serial_B1056  Serial_B1058  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2             0             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   Serial_B1059  Serial_B1060  Serial_B1062  
0             0             0             0  
1             0             0             0  
2             0             0             0  
3             0             0             0  
4             0             0             0  

[5 rows x 89 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 89 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Unnamed: 0                           90 non-null     int64  
 1   PayloadMass                          90 non-null     float64
 2   Flights                              90 non-null     int64  
 3   GridFins                             90 non-null     int64  
 4   Reused                               90 non-null     int64  
 5   Legs                                 90 non-null     int64  
 6   Block                                90 non-null     float64
 7   ReusedCount                          90 non-null     int64  
 8   Class                                90 non-null     int64  
 9   Orbit_ES-L1                          90 non-null     int64  
 10  Orbit_GEO                            90 non-null     int64  
 11  Orbit_GTO                         

In [5]:
X = df.drop("Class", axis= 1)
y = df["Class"]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 101)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
tree = DecisionTreeClassifier()

In [10]:
tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [11]:
Prediction = tree.predict(X_test)

In [12]:
Prediction

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1], dtype=int64)

In [13]:
y_test

50    0
6     1
51    0
54    1
53    1
69    1
32    1
31    1
21    1
88    1
43    1
47    0
3     0
1     0
74    0
16    1
45    0
25    1
2     0
13    0
56    1
76    0
73    1
41    1
14    0
23    1
37    1
Name: Class, dtype: int64

In [14]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [15]:
confusion_matrix(y_test, Prediction)

array([[ 9,  2],
       [ 1, 15]], dtype=int64)

In [16]:
accuracy_score(y_test, Prediction, normalize= False)

24

In [17]:
accuracy_score(y_test, Prediction, normalize= True)

0.8888888888888888

In [18]:
print(classification_report(y_test, Prediction))

              precision    recall  f1-score   support

           0       0.90      0.82      0.86        11
           1       0.88      0.94      0.91        16

    accuracy                           0.89        27
   macro avg       0.89      0.88      0.88        27
weighted avg       0.89      0.89      0.89        27



In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
tree_1 = DecisionTreeClassifier()

In [21]:
parameters = {"min_samples_leaf": [1, 2, 4],
              "min_samples_split": [2, 5]}

In [22]:
tree_cv = GridSearchCV(tree_1, parameters)

In [23]:
tree_cv.fit(X_train, y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5]})

In [24]:
print("tuned hpyerparameters :(best parameters) ", tree_cv.best_params_)

tuned hpyerparameters :(best parameters)  {'min_samples_leaf': 1, 'min_samples_split': 2}


In [25]:
tree_1 = DecisionTreeClassifier(min_samples_leaf= 1, min_samples_split= 5)

In [26]:
tree_1.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_split=5)

In [27]:
Prediction_1 = tree_1.predict(X_test)

In [28]:
Prediction_1

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1], dtype=int64)

In [29]:
confusion_matrix(y_test, Prediction_1)

array([[ 9,  2],
       [ 1, 15]], dtype=int64)

In [30]:
accuracy_score(y_test, Prediction_1, normalize= False)

24

In [31]:
accuracy_score(y_test, Prediction_1, normalize= True)

0.8888888888888888

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rfc = RandomForestClassifier()

In [34]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [35]:
rfc_predict = rfc.predict(X_test)

In [36]:
rfc_predict

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1], dtype=int64)

In [37]:
confusion_matrix(y_test, rfc_predict)

array([[ 8,  3],
       [ 2, 14]], dtype=int64)

In [38]:
accuracy_score(y_test, rfc_predict, normalize= False)

22

In [39]:
accuracy_score(y_test, rfc_predict, normalize= True)

0.8148148148148148

In [40]:
print(classification_report(y_test, rfc_predict))

              precision    recall  f1-score   support

           0       0.80      0.73      0.76        11
           1       0.82      0.88      0.85        16

    accuracy                           0.81        27
   macro avg       0.81      0.80      0.81        27
weighted avg       0.81      0.81      0.81        27



In [41]:
rfc_1 = RandomForestClassifier()

In [42]:
parameters_rfc = {"min_samples_leaf": [1, 2, 4],
                  "min_samples_split": [2, 5, 10],
                  "n_estimators": [10,20,30]}

In [43]:
rfc_cv = GridSearchCV(rfc_1, parameters_rfc)

In [44]:
rfc_cv.fit(X_train, y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [10, 20, 30]})

In [45]:
print("tuned hpyerparameters :(best parameters) ", rfc_cv.best_params_)

tuned hpyerparameters :(best parameters)  {'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 10}


In [46]:
rfc_1 = RandomForestClassifier(n_estimators= 10,
                               min_samples_leaf= 1, 
                               min_samples_split= 2)

In [47]:
rfc_1.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10)

In [48]:
rfc_predictions_1 = rfc_1.predict(X_test)

In [49]:
rfc_predictions_1

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1], dtype=int64)

In [50]:
confusion_matrix(y_test, rfc_predictions_1)

array([[10,  1],
       [ 0, 16]], dtype=int64)

In [51]:
accuracy_score(y_test, rfc_predictions_1, normalize= False) 

26

In [52]:
accuracy_score(y_test, rfc_predictions_1, normalize= True) 

0.9629629629629629

In [53]:
print(classification_report(y_test, rfc_predictions_1))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.94      1.00      0.97        16

    accuracy                           0.96        27
   macro avg       0.97      0.95      0.96        27
weighted avg       0.97      0.96      0.96        27

