In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("preprocessed_dataset.csv")

In [3]:
df.head()

Unnamed: 0  PayloadMass  Flights  GridFins  Reused  Legs  Block  \
0           0  6104.959412        1         0       0     0    1.0   
1           1   525.000000        1         0       0     0    1.0   
2           2   677.000000        1         0       0     0    1.0   
3           3   500.000000        1         0       0     0    1.0   
4           4  3170.000000        1         0       0     0    1.0   

   ReusedCount  Class  Orbit_ES-L1  ...  Serial_B1048  Serial_B1049  \
0            0      0            0  ...             0             0   
1            0      0            0  ...             0             0   
2            0      0            0  ...             0             0   
3            0      0            0  ...             0             0   
4            0      0            0  ...             0             0   

   Serial_B1050  Serial_B1051  Serial_B1054  Serial_B1056  Serial_B1058  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2             0             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   Serial_B1059  Serial_B1060  Serial_B1062  
0             0             0             0  
1             0             0             0  
2             0             0             0  
3             0             0             0  
4             0             0             0  

[5 rows x 89 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 89 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Unnamed: 0                           90 non-null     int64  
 1   PayloadMass                          90 non-null     float64
 2   Flights                              90 non-null     int64  
 3   GridFins                             90 non-null     int64  
 4   Reused                               90 non-null     int64  
 5   Legs                                 90 non-null     int64  
 6   Block                                90 non-null     float64
 7   ReusedCount                          90 non-null     int64  
 8   Class                                90 non-null     int64  
 9   Orbit_ES-L1                          90 non-null     int64  
 10  Orbit_GEO                            90 non-null     int64  
 11  Orbit_GTO                         

In [5]:
X = df.drop("Class", axis= 1)
y= df["Class"]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 101)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knn = KNeighborsClassifier(n_neighbors= 10)

In [10]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [11]:
Prediction = knn.predict(X_test)

In [12]:
Prediction

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [13]:
y_test

50    0
6     1
51    0
54    1
53    1
69    1
32    1
31    1
21    1
88    1
43    1
47    0
3     0
1     0
74    0
16    1
45    0
25    1
Name: Class, dtype: int64

In [14]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [15]:
confusion_matrix(y_test, Prediction)

array([[2, 5],
       [3, 8]], dtype=int64)

In [16]:
accuracy_score(y_test, Prediction, normalize= False)

10

In [17]:
accuracy_score(y_test, Prediction, normalize= True)

0.5555555555555556

In [18]:
print(classification_report(y_test, Prediction))

              precision    recall  f1-score   support

           0       0.40      0.29      0.33         7
           1       0.62      0.73      0.67        11

    accuracy                           0.56        18
   macro avg       0.51      0.51      0.50        18
weighted avg       0.53      0.56      0.54        18



In [19]:
knn_1 = KNeighborsClassifier()

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
Parameters = {"n_neighbors": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}

In [22]:
knn_cv = GridSearchCV(knn_1, Parameters)

In [23]:
knn_cv.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [24]:
Prediction_1 = knn_cv.predict(X_test)

In [25]:
Prediction_1

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [26]:
confusion_matrix(y_test, Prediction_1)

array([[2, 5],
       [2, 9]], dtype=int64)

In [27]:
accuracy_score(y_test, Prediction_1, normalize= False)

11

In [28]:
accuracy_score(y_test, Prediction_1, normalize= True)

0.6111111111111112

In [29]:
print(classification_report(y_test, Prediction_1))

              precision    recall  f1-score   support

           0       0.50      0.29      0.36         7
           1       0.64      0.82      0.72        11

    accuracy                           0.61        18
   macro avg       0.57      0.55      0.54        18
weighted avg       0.59      0.61      0.58        18

