In [1]:
import numpy as np

In [2]:
lst_1 = [1, 2, 3, 4, 5]
lst_1

[1, 2, 3, 4, 5]

In [3]:
np.array(lst_1)

array([1, 2, 3, 4, 5])

In [5]:
matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [17]:
np.linspace(4, 63, 20)

array([ 4.        ,  7.10526316, 10.21052632, 13.31578947, 16.42105263,
       19.52631579, 22.63157895, 25.73684211, 28.84210526, 31.94736842,
       35.05263158, 38.15789474, 41.26315789, 44.36842105, 47.47368421,
       50.57894737, 53.68421053, 56.78947368, 59.89473684, 63.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.rand(3)

array([0.0065033 , 0.88486244, 0.62670588])

In [19]:
np.random.rand(50)

array([0.88037305, 0.24539414, 0.06108571, 0.68504023, 0.67076982,
       0.3032718 , 0.87978173, 0.91258253, 0.87896292, 0.35846034,
       0.23941817, 0.13183685, 0.52455721, 0.75456153, 0.8117351 ,
       0.6978592 , 0.62990466, 0.50551703, 0.76411833, 0.29882803,
       0.18662878, 0.32948234, 0.63340282, 0.52766173, 0.01711371,
       0.19809597, 0.00203132, 0.73824384, 0.85137029, 0.15175481,
       0.09692099, 0.39631853, 0.45119669, 0.93775557, 0.19213595,
       0.16488085, 0.70522972, 0.86510144, 0.44900875, 0.42222452,
       0.65298457, 0.31710695, 0.32093655, 0.89129143, 0.21133865,
       0.99521197, 0.57785512, 0.83434141, 0.98373652, 0.15176162])

In [22]:
np.random.rand(7, 7)

array([[0.30983077, 0.22927354, 0.3775365 , 0.84353198, 0.68573331,
        0.91076428, 0.04062073],
       [0.94085898, 0.12991077, 0.11943691, 0.51047351, 0.63333702,
        0.93648791, 0.89362894],
       [0.67670049, 0.73093977, 0.55007629, 0.10204041, 0.97641536,
        0.19103772, 0.10992385],
       [0.75316658, 0.62267962, 0.24087388, 0.37558792, 0.34233842,
        0.36247585, 0.26458288],
       [0.79029447, 0.25249683, 0.18777914, 0.76345947, 0.03694479,
        0.69993331, 0.48849984],
       [0.16584419, 0.57171439, 0.73149289, 0.09503765, 0.39223142,
        0.5328148 , 0.21461379],
       [0.43447146, 0.87435533, 0.30750782, 0.7077698 , 0.86839029,
        0.63113878, 0.09194574]])

In [23]:
np.random.randint(100, 3500)

3465

In [24]:
np.random.randint(100, 700, 15)

array([343, 394, 403, 170, 532, 461, 491, 411, 242, 546, 569, 217, 426,
       658, 611])

In [26]:
arang = np.arange(25)
arang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arang.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arang.shape

(25,)

In [36]:
arang.dtype

dtype('int32')

In [37]:
type(arang)

numpy.ndarray

In [38]:
arang.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arang.reshape(1, 25).shape

(1, 25)

In [39]:
arang.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [41]:
arang.reshape(25, 1).shape

(25, 1)

In [28]:
rand = np.random.randint(0, 70, 10)
rand

array([26, 33, 48, 56,  2,  5, 17, 60, 11,  6])

In [29]:
rand.max()

60

In [30]:
rand.argmax()

7

In [31]:
rand.min()

2

In [32]:
rand.argmin()

4